# Generated by Django 5.1.1 on 2024-09-07 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_order_orderitem_cart'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'menuitem')},
        ),
    ]
